### ISSUE TITLE
AEM Translation Framework - Bootstrap connector

### ISSUE THREAD

**Issue by sridharjayakumar** [Adobe-Marketing-Cloud/manage#3]
We have built a bootstrap connector using the Translation Framework API for AEM 6.1.0. The purpose of the connector is to 
- Provide sample code to Translation providers to start building their connector
- Provide best practices for building/packaging the connector and 
- Highlight the standards for out Connector certification process
- Serve as a reference implementation of the Translation API

**Comment by akshaymad** [comment]
+1, thanks Sridhar for initiating this.

**Comment by paolomoz** [comment]
Repo created. Have fun!
https://github.com/Adobe-Marketing-Cloud/aem-translation-framework-bootstrap-connector
